version: "3.1"
services:
    apache:
        build: 
            context: ./docker/apache/
        restart: always
        container_name: xiavic-apache
        ports:
            - "${XIAVIC_APACHE_PORT}:80"
        volumes:
            - ./application:/var/www/html:delegated
            - ./docker/apache/logs:/var/log/apache2:delegated
